"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
type Order={id:string;order_number:string;customer_name:string;phone:string;email?:string;address?:string;pin_code?:string;total:number;subtotal:number;shipping:number;cod_fee:number;payment_method:string;payment_status:string;fulfillment_status:string;created_at:string};
type Product={id:string;slug:string;name:string;description?:string;price:number;compare_at_price?:number|null;unit?:string;category?:string;inventory:number;image_url?:string;active:boolean};
const empty={slug:"",name:"",description:"",price:"",compareAtPrice:"",unit:"",category:"",inventory:"0",imageUrl:"",active:true};
export default function AdminPage(){
 const [orders,setOrders]=useState<Order[]>([]),[catalog,setCatalog]=useState<Product[]>([]);
 const [token]=useState("direct-admin"),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const [form,setForm]=useState<any>(empty),[editing,setEditing]=useState<string|null>(null),[saving,setSaving]=useState(false),[msg,setMsg]=useState(""),[activeView,setActiveView]=useState("overview");
 const headers=()=>({"Content-Type":"application/json"});
 async function load(){setLoading(true);setError("");try{const h={Authorization:"Bearer "+token};const [o,p]=await Promise.all([fetch("/api/admin/orders",{headers:h}),fetch("/api/admin/products",{headers:h})]);const od=await o.json(),pd=await p.json();if(!o.ok||!p.ok)throw new Error(od.error||pd.error||"Admin API unavailable.");setOrders(od.orders||[]);setCatalog(pd.products||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}));
 const revenue=useMemo(()=>orders.reduce((n,o)=>n+Number(o.total||0),0),[orders]);
 const lowStock=catalog.filter(p=>p.inventory<10).length;
 async function productSave(e:any){e.preventDefault();setSaving(true);setMsg("");try{const r=await fetch("/api/admin/products",{method:editing?"PATCH":"POST",headers:headers(),body:JSON.stringify(editing?{id:editing,...form}:form)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Save failed.");setMsg(editing?"Product changes saved.":"Product added to catalog.");setForm(empty);setEditing(null);await load()}catch(e){setMsg(e instanceof Error?e.message:"Save failed.")}finally{setSaving(false)}}
 function edit(p:Product){setEditing(p.id);setForm({slug:p.slug,name:p.name,description:p.description||"",price:String(p.price),compareAtPrice:p.compare_at_price==null?"":String(p.compare_at_price),unit:p.unit||"",category:p.category||"",inventory:String(p.inventory),imageUrl:p.image_url||"",active:p.active});setActiveView("products");window.scrollTo({top:0,behavior:"smooth"})}
 async function remove(id:string){if(!confirm("Delete this product?"))return;const r=await fetch("/api/admin/products",{method:"DELETE",headers:headers(),body:JSON.stringify({id})});const d=await r.json();if(!r.ok){setError(d.error||"Delete failed.");return}await load()}
 async function orderUpdate(id:string,key:string,value:string){const r=await fetch("/api/admin/orders",{method:"PATCH",headers:headers(),body:JSON.stringify({id,[key]:value})});const d=await r.json();if(!r.ok){setError(d.error||"Order update failed.");return}await load()}
 const nav=[{id:"overview",label:"Overview",mark:"◫"},{id:"products",label:"Products",mark:"▧"},{id:"orders",label:"Orders",mark:"↗"}];
 return <main className="vxAdmin">
  <aside className="vxSidebar"><Link href="/" className="vxBrand"><span className="vxBrandMark">V</span><span>VERDIXA<small>BOTANICAL GOODS</small></span></Link><div className="vxSideCaption">WORKSPACE</div><nav className="vxSideNav">{nav.map(n=><button key={n.id} className={activeView===n.id?"selected":""} onClick={()=>{setActiveView(n.id);document.getElementById("vx-"+n.id)?.scrollIntoView({behavior:"smooth",block:"start"})}}><span className="vxNavMark">{n.mark}</span>{n.label}{n.id==="orders"&&<i>{orders.length}</i>}</button>)}</nav><div className="vxSideBottom"><span className="vxAvatar">V</span><div><b>Store operator</b><small>Verdixa workspace</small></div><span className="vxSideDots">···</span></div></aside>
  <div className="vxWorkspace">
   <header className="vxTopbar"><div><span className="vxCrumb">Workspace</span><span className="vxCrumbSlash">/</span><b>{nav.find(n=>n.id===activeView)?.label||"Overview"}</b></div><div className="vxTopActions"><span className="vxStoreStatus"><i/> Store connected</span><Link href="/" className="vxStoreLink">Visit store ↗</Link><button className="vxRefresh" onClick={load} disabled={loading}>{loading?"Refreshing…":"↻ Refresh"}</button></div></header>
   <div className="vxContent">
    {error&&<div className="vxError"><b>Something needs attention</b><span>{error}</span><button onClick={()=>setError("")}>Dismiss ×</button></div>}
    <section className="vxWelcome" id="vx-overview"><div><span className="vxKicker">YOUR STORE AT A GLANCE</span><h1>Good things<br/><em>are growing.</em></h1><p>Manage your botanical collection, track incoming orders, and keep your store in good shape.</p><button className="vxPrimary" onClick={()=>{setActiveView("products");document.getElementById("vx-products")?.scrollIntoView({behavior:"smooth"})}}>Manage collection <span>↗</span></button></div><div className="vxWelcomeArt" aria-hidden="true"><div className="vxArtCircle"/><div className="vxArtLeaf vxLeafOne"/><div className="vxArtLeaf vxLeafTwo"/><div className="vxArtStem"/><span>GROW WITH INTENTION</span></div></section>
    <section className="vxMetricGrid"><article className="vxMetric vxMetricDark"><div><span>TOTAL REVENUE</span><span className="vxMetricIcon">₹</span></div><strong>₹{revenue.toLocaleString("en-IN")}</strong><small>From {orders.length} loaded orders</small><div className="vxMetricFoot"><span>ORDER VALUE</span><span>↗</span></div></article><article className="vxMetric"><div><span>ORDERS RECEIVED</span><span className="vxMetricIcon">↗</span></div><strong>{String(orders.length).padStart(2,"0")}</strong><small>Recent orders in your workspace</small><div className="vxMetricFoot"><span>ALL CHANNELS</span><span>→</span></div></article><article className="vxMetric"><div><span>PRODUCTS LISTED</span><span className="vxMetricIcon">◇</span></div><strong>{String(catalog.length).padStart(2,"0")}</strong><small>{lowStock?lowStock+" products need a stock check":"Keep your collection up to date"}</small><div className="vxMetricFoot"><span>CATALOG HEALTH</span><span>→</span></div></article></section>
    <section className="vxSection" id="vx-products"><div className="vxSectionHead"><div><span className="vxKicker">COLLECTION / 01</span><h2>{editing?"Refine a product":"Your products"}</h2><p>Maintain the details behind every botanical ritual.</p></div><span className="vxCountPill">{catalog.length} ITEMS</span></div>
     <div className="vxProductLayout"><div className="vxProductList"><div className="vxTableHead"><span>PRODUCT</span><span>PRICE</span><span>INVENTORY</span><span>STATUS</span><span>ACTION</span></div>
      {catalog.length?catalog.map(p=><div className="vxProductLine" key={p.id}><div className="vxProductName">{p.image_url?<img src={p.image_url} alt=""/>:<div className="vxProductPlaceholder">V.</div>}<div><b>{p.name}</b><small>{p.category||"BOTANICAL"} · {p.unit||"—"}</small></div></div><strong className="vxPrice">₹{Number(p.price).toLocaleString("en-IN")}</strong><span className={p.inventory<10?"vxStockLow":"vxStock"}><i/>{p.inventory} units</span><span className={p.active?"vxPublished":"vxDraft"}>{p.active?"Published":"Draft"}</span><div className="vxActions"><button onClick={()=>edit(p)}>Edit ↗</button><button aria-label={"Delete "+p.name} onClick={()=>remove(p.id)}>×</button></div></div>):<div className="vxEmpty">Your collection is waiting. Add your first product using the form.</div>}</div>
      <aside className="vxFormCard"><div className="vxFormIntro"><span className="vxKicker">{editing?"PRODUCT EDITOR":"NEW ADDITION"}</span><h3>{editing?"Update details":"Add to collection"}</h3><p>Carefully enter the details that customers will see.</p></div><form className="vxProductForm" onSubmit={productSave}>
       <label>PRODUCT NAME<input required value={form.name} onChange={e=>set("name",e.target.value)} placeholder="e.g. Pure Moringa Powder"/></label><label>URL SLUG<input required value={form.slug} onChange={e=>set("slug",e.target.value)} placeholder="pure-moringa-powder"/></label>
       <div className="vxFormPair"><label>PRICE (₹)<input required type="number" min="0" value={form.price} onChange={e=>set("price",e.target.value)} placeholder="299"/></label><label>COMPARE PRICE<input type="number" min="0" value={form.compareAtPrice} onChange={e=>set("compareAtPrice",e.target.value)} placeholder="Optional"/></label></div>
       <div className="vxFormPair"><label>UNIT / SIZE<input value={form.unit} onChange={e=>set("unit",e.target.value)} placeholder="100 G"/></label><label>CATEGORY<input value={form.category} onChange={e=>set("category",e.target.value)} placeholder="MORINGA"/></label></div>
       <div className="vxFormPair"><label>STOCK COUNT<input type="number" min="0" value={form.inventory} onChange={e=>set("inventory",e.target.value)} placeholder="0"/></label><label>IMAGE PATH<input value={form.imageUrl} onChange={e=>set("imageUrl",e.target.value)} placeholder="/products/image.jpg"/></label></div>
       <label>DESCRIPTION<textarea value={form.description} onChange={e=>set("description",e.target.value)} placeholder="A short description of this product…"/></label><label className="vxPublishToggle"><input type="checkbox" checked={form.active} onChange={e=>set("active",e.target.checked)}/><span><b>Publish product</b><small>Make this product visible in your store</small></span></label>
       <button className="vxSubmit" disabled={saving}>{saving?"Saving changes…":editing?"Save product changes":"Add product to store"} <span>↗</span></button>{editing&&<button type="button" className="vxCancel" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel editing</button>}{msg&&<p className="vxFormMessage">{msg}</p>}
      </form></aside></div></section>
    <section className="vxSection vxOrdersSection" id="vx-orders"><div className="vxSectionHead"><div><span className="vxKicker">FULFILMENT / 02</span><h2>Orders in motion</h2><p>Review customer orders and update their journey.</p></div><span className="vxCountPill">{orders.length} ORDERS</span></div>
     <div className="vxOrdersTable"><div className="vxOrderHead"><span>ORDER / CUSTOMER</span><span>ORDER TOTAL</span><span>PAYMENT</span><span>FULFILMENT</span></div>{orders.length?orders.map(o=><article className="vxOrderLine" key={o.id}><div className="vxOrderCustomer"><b>{o.order_number}</b><span>{o.customer_name} · {o.phone}</span><small>{o.address||""} {o.pin_code||""}</small></div><strong>₹{Number(o.total).toLocaleString("en-IN")}</strong><div className="vxStatusCell"><span className={"vxPayTag "+o.payment_status}>{o.payment_status}</span><select aria-label={"Payment status for "+o.order_number} value={o.payment_status} onChange={e=>orderUpdate(o.id,"payment_status",e.target.value)}><option>pending</option><option>paid</option><option>failed</option><option>refunded</option></select></div><select className="vxFulfilSelect" aria-label={"Fulfilment status for "+o.order_number} value={o.fulfillment_status} onChange={e=>orderUpdate(o.id,"fulfillment_status",e.target.value)}><option>pending</option><option>processing</option><option>shipped</option><option>delivered</option><option>cancelled</option></select></article>):<div className="vxEmpty">No orders to show yet. New customer orders will appear here.</div>}</div></section>
    <footer className="vxFooter"><span>VERDIXA <i>·</i> COMMERCE WORKSPACE</span><span>Made with care for the everyday ritual.</span><Link href="/">Back to storefront ↗</Link></footer>
   </div>
  </div>
 </main>
}
