"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
type Order={id:string;order_number:string;customer_name:string;phone:string;total:number;payment_method:string;payment_status:string;fulfillment_status:string;created_at:string};
type Product={id:string;name:string;price:number;inventory:number;active:boolean;category:string};
export default function AdminPage(){
 const [orders,setOrders]=useState<Order[]>([]);const [catalog,setCatalog]=useState<Product[]>([]);const [token,setToken]=useState("");const [loading,setLoading]=useState(false);const [error,setError]=useState("");
 async function load(){if(!token)return;setLoading(true);setError("");try{const h={Authorization:"Bearer "+token};const [o,p]=await Promise.all([fetch("/api/admin/orders",{headers:h}),fetch("/api/admin/products",{headers:h})]);if(!o.ok||!p.ok)throw new Error("Invalid admin token or API unavailable.");const od=await o.json(),pd=await p.json();setOrders(od.orders||[]);setCatalog(pd.products||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard.")}finally{setLoading(false)}}
 useEffect(()=>{const saved=localStorage.getItem("verdixa_admin_token");if(saved){setToken(saved)}},[]);
 const save=()=>{localStorage.setItem("verdixa_admin_token",token);load()};
 return <main className="adminPage"><header className="adminHeader"><div><p className="eyebrow">VERDIXA DASHBOARD</p><h1>Commerce control.</h1></div><Link href="/" className="adminBack">View storefront →</Link></header><section className="adminAuth"><input value={token} onChange={e=>setToken(e.target.value)} placeholder="Admin dashboard token"/><button className="primary" onClick={save}>Connect</button></section>{error&&<p className="adminError">{error}</p>}<section className="adminStats"><article><span>Products</span><strong>{catalog.length}</strong><small>From Supabase</small></article><article><span>Orders</span><strong>{orders.length}</strong><small>Latest 100</small></article><article><span>Revenue</span><strong>₹{orders.reduce((n,o)=>n+Number(o.total||0),0)}</strong><small>Loaded orders</small></article></section><section className="adminPanel"><div className="adminPanelHead"><div><p className="eyebrow">ORDERS</p><h2>Recent orders</h2></div><span>{loading?"Refreshing…":"Live API"}</span></div><div className="adminTable">{orders.length?orders.map(o=><div className="adminRow" key={o.id}><div><b>{o.order_number}</b><small>{o.customer_name} · {o.phone}</small></div><strong>₹{o.total}</strong><span>{o.payment_method} · {o.payment_status}</span><span>{o.fulfillment_status}</span></div>):<p className="adminEmpty">No orders loaded yet.</p>}</div></section><section className="adminPanel"><div className="adminPanelHead"><div><p className="eyebrow">CATALOG</p><h2>Products</h2></div><span>{catalog.length} items</span></div><div className="adminTable">{catalog.map(p=><div className="adminRow" key={p.id}><div><b>{p.name}</b><small>{p.category}</small></div><strong>₹{p.price}</strong><span>{p.inventory} in stock</span><span>{p.active?"Published":"Draft"}</span></div>)}</div></section></main>}